### ISSUE TITLE
Review Shop

### ISSUE THREAD

**Issue by eniluck** [FanTei/MyWork#8]
по домашке SHOP https://github.com/FanTei/MyWork/tree/Main/Shop
По гиту:
1. Закинь gitignore для visual studio в папку с проектом. Тот который у тебя лежит в корне репозитория не удаляет генерируемые файлы. в репозитории они не нужны. 
2. Удали лишние папки .vs/Shop, bin/Debug, obj
3. Сделай коммит с нормальным описанием "Удалил ненужные файлы" 

По форматированию кода: 
Добавляй пустую строку между методами и логическими блоками. Вот например я немного переделал твой класс, добавил пустые строки и уже смотрится более читаемо: https://github.com/eniluck/MyWork/blob/refactoring/Shop/Shop/Model/Market.cs 

По коду: 
У тебя очень много повторяющегося кода в классах: Product,Showcase, Market а именно в методах  ShopUsing, Interect Вынеси работу с консолью отсюда в отдельный класс.  

Если что непонятно пиши тут, или в телеграмм канал.

**Comment by FanTei** [comment]
https://github.com/FanTei/MyWork
Начал испралять.
Не могу понять только как не создать обьекты showcase и product в классе Application.

**Comment by FanTei** [comment]
https://github.com/FanTei/MyWork 
Переделал)

**Comment by eniluck** [comment]
Супер!

Хорошо что даешь осмысленные называния для коммитов типа - FixingShop. но надо ещё что то добавлять. Например "убрал лишние пробелы" или "добавил метод для добавления продукта" в общем все что происходит у тебя в коде старайся кратко описать.

по гиту то что раньше я просил удалить все ещё находится в репозитории. 
вот этих папок и всего их содержимого в репозитории не должно быть :
- https://github.com/FanTei/MyWork/tree/Main/Shop/.vs/Shop
- https://github.com/FanTei/MyWork/tree/Main/Shop/Shop/bin/Debug/netcoreapp3.1
- https://github.com/FanTei/MyWork/tree/Main/Shop/Shop/obj

по форматированию ты постарался. но можно ещё доделать :)

по коду:  
- сделай описание всех методов ( https://docs.microsoft.com/ru-ru/dotnet/csharp/codedoc#walkthrough ) 
- переделай методы ValidatePrice и Validate.  Чтобы они спрашивали пользователя о чем то и ждали ввода. 
Сейчас у тебя есть код, который не нужен. [Например переменная x нигде не участвует] (https://github.com/FanTei/MyWork/blob/c4cebf57b7bf89663cb46bda4d7f551a4b9c3fc2/Shop/Shop/Model/Application.cs#L42)

Дальше ещё порефаторим код :) клёво что не сдаешься :)

**Comment by FanTei** [comment]
Все исправил теперь должно быть без замечаний:)
https://github.com/FanTei/MyWork/tree/Main/Shop

**Comment by FanTei** [comment]
Что-то еще нужно исправить или на основе этого можно клиент-сервер делать?

**Comment by eniluck** [comment]
У тебя гитигнор от c++ а надо от визуал студии.
https://github.com/github/gitignore/blob/master/C%2B%2B.gitignore 
https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

**Comment by eniluck** [comment]
1. Не реализован выход из программы. когда пользователь захочет. или возврат в основное меню.

2. Есть цикл в классе Program
while (true)
  market.Start();
Но market.Start выполняется один раз в нём.
У тебя во всей программе вместо цикла используется рекурсия. и это очень усложняет чтение программы.
По идее тебе Рома советовал в Application вынести основной цикл программы.

3. В классе Market есть public свойства Showcases и Products они должны быть приватные и вся логика по работе с ними должна быть в классе Market.

**Comment by FanTei** [comment]
Все исправил!
Поля  конечно сделал приватными но не совсем понимаю зачем надо выносить всю логику взаимодействия с product и showcase в класса Market 
Если я всю логику вынесу в Market он получиться слишком большим и не читабельным и классы Market и Showcase станут просто набором свойств

**Comment by eniluck** [comment]
Давай посмотрим на класс Product. 
Он сейчас знает о всём магазине Market и других продуктах List<Product> и как следствие теперь в магазине будет анархия если каждый продукт будет решать какая цена будет у другого продукта. 
По сути этот класс должен только хранить поля с его данными, выдавать информацию о себе, может ещё содержать какие то методы по работе с его данными. 
Можно добавить ещё один класс для работы со всеми продуктами, который будет создавать продукт, редактировать, находить и т.д.

**Comment by FanTei** [comment]
Получается в класс showcase можно не трогать а из класса product перенести в market только те методы которые отвечают именно за продукт на витрине

**Comment by eniluck** [comment]
Ок. Может быть тут уже глаза замылились. Давай некст проекты делать :)
